Домашнее задание numpy 
список вариантов по фамилиям: 

Егор Бобошко - 1 вариант 

Тарон Вирабян - 2 вариант 

Эрик Гарифуллин - 3 вариант 

Дмитрий Гусаров - 4 вариант 

Даниил Жданов - 5 вариант 

Даниил Иванов - 6 вариант 

Никита Иващенко -  7 вариант 

Роман Кислинский - 8 вариант 

Семен Квасенко - 9 вариант 

Евгений Кушаков - 10 вариант 

Денис Култушев - 11 вариант 

Тимур Мендгалиев - 12 вариант 

Иван Насонов - 13 вариант 

Андрей Овсянов - 14 вариант 

Афина Подерни - 15 вариант 

Анна Павликова - 16 вариант 

Людмила Петрашко - 17 вариант 

Дарья Урядова - 18 вариант 

Максим Чеботарев - 19 вариант 

Кирилл Чернов - 20 вариант 

Никита Щиголев - 21 вариант 

Илья Цыганов - 22 вариант 


<h1>Задание 1</h1>

На маркетплейсе есть огромный объем данных содержащий записи о продажах различных продуктов. Наша цель — рассчитать общий доход, полученный от каждого продукта за определённый период. 

Необходимо решить задачу через классический python, numpy и numpy с использованием векторизации


Данные: 
products = ['автомобиль HAVAL', 'обувь', 'одежда', 'телефоны'] (при решении через numpy необходимо представить это в виде np.array() )
prices = [20000, 3000, 45600, 5000] (при решении через numpy необходимо представить это в виде np.array() ) 

Данные о продажах необходимо сгенерировать самостоятельно и вывести в одном параграфов в ноутбуке, ниже приведен пример генерации случайных значений 

In [1]:
# пример генерации на python

import random
variant = 0 # подставьте номер своего  варианта
sales = [random.randint(0, variant+100) for i in range(100000)]
print(sales)

[16, 9, 59, 37, 74, 85, 9, 44, 51, 1, 94, 70, 73, 83, 89, 63, 49, 0, 87, 40, 22, 49, 40, 52, 91, 19, 19, 30, 17, 83, 49, 48, 38, 1, 70, 78, 80, 88, 16, 23, 16, 87, 51, 17, 13, 71, 48, 77, 85, 95, 56, 50, 34, 91, 99, 99, 36, 26, 6, 87, 87, 39, 16, 49, 24, 82, 33, 93, 2, 92, 67, 46, 28, 10, 82, 44, 59, 10, 5, 36, 1, 51, 57, 70, 70, 25, 89, 1, 0, 70, 24, 55, 70, 37, 72, 73, 17, 40, 25, 86, 4, 20, 90, 32, 92, 81, 16, 28, 63, 23, 35, 45, 54, 35, 46, 92, 9, 45, 56, 40, 15, 43, 86, 43, 64, 85, 15, 57, 11, 74, 18, 65, 3, 88, 37, 95, 87, 11, 9, 14, 4, 62, 15, 11, 4, 8, 69, 15, 7, 75, 15, 36, 67, 80, 69, 60, 52, 2, 36, 57, 12, 78, 62, 6, 96, 55, 42, 96, 50, 67, 87, 8, 23, 48, 14, 23, 3, 22, 48, 19, 59, 36, 52, 70, 96, 79, 81, 100, 68, 51, 36, 69, 40, 53, 85, 47, 23, 98, 6, 37, 39, 19, 12, 75, 16, 16, 96, 67, 59, 9, 75, 4, 72, 60, 24, 72, 22, 50, 77, 22, 31, 89, 13, 28, 20, 82, 60, 63, 5, 98, 44, 50, 86, 28, 28, 73, 92, 24, 45, 36, 29, 14, 84, 45, 96, 19, 22, 23, 43, 34, 91, 78, 48, 4, 26, 100, 4

Данные в различных реализациях должны совпадать.

После генерации необходимо сравнить доход от каждого продукта и время на выполнение. 

# *Генерация Данных*

In [2]:
import numpy as np
import random

In [3]:
variant = 3

In [4]:
products = ['автомобиль HAVAL', 'обувь', 'одежда', 'телефоны']
prices = [20000, 3000, 45600, 5000]

In [5]:
auto_sales = [random.randint(0, variant + 100) for i in range(100000)]
print(auto_sales[:100])


[62, 36, 5, 103, 55, 7, 15, 70, 100, 17, 52, 80, 22, 83, 32, 78, 58, 65, 3, 51, 91, 98, 48, 86, 36, 99, 37, 73, 71, 79, 69, 27, 100, 85, 95, 5, 101, 85, 56, 15, 25, 33, 59, 29, 62, 72, 16, 29, 90, 29, 15, 22, 50, 84, 20, 70, 54, 99, 51, 68, 10, 42, 49, 7, 55, 19, 93, 57, 35, 93, 62, 3, 48, 13, 63, 41, 37, 63, 95, 81, 47, 55, 15, 38, 80, 65, 37, 58, 10, 90, 97, 16, 67, 60, 6, 35, 23, 61, 61, 90]


In [6]:
shoes_sales = [random.randint(0, variant + 100) for i in range(100000)]
print(shoes_sales[:100])


[10, 18, 10, 15, 4, 25, 78, 103, 40, 14, 62, 89, 103, 61, 13, 64, 52, 11, 37, 17, 27, 103, 57, 11, 14, 93, 68, 14, 60, 36, 65, 25, 69, 19, 73, 13, 62, 5, 7, 54, 61, 94, 21, 92, 88, 63, 97, 17, 79, 20, 102, 35, 41, 67, 24, 66, 20, 88, 22, 81, 74, 75, 24, 86, 88, 4, 65, 90, 28, 12, 42, 80, 47, 93, 71, 70, 31, 62, 93, 2, 81, 89, 93, 29, 8, 101, 10, 6, 4, 50, 44, 72, 45, 22, 11, 37, 55, 73, 71, 70]


In [7]:
clothes_sales = [random.randint(0, variant + 100) for i in range(100000)]
print(clothes_sales[:100])

[27, 19, 55, 61, 101, 89, 63, 14, 89, 35, 71, 63, 74, 74, 68, 29, 91, 66, 14, 87, 79, 68, 50, 7, 94, 96, 68, 25, 59, 50, 27, 68, 22, 103, 11, 63, 69, 7, 21, 26, 42, 77, 0, 66, 47, 73, 54, 63, 101, 57, 11, 46, 91, 22, 25, 90, 45, 26, 42, 63, 38, 26, 58, 30, 31, 88, 73, 58, 17, 2, 91, 62, 37, 26, 13, 4, 64, 25, 48, 103, 77, 47, 85, 90, 95, 99, 96, 101, 92, 86, 57, 29, 31, 66, 4, 44, 33, 82, 59, 65]


In [8]:
mobile_sales = [random.randint(0, variant + 100) for i in range(100000)]
print(mobile_sales[:100])

[0, 29, 90, 17, 57, 74, 50, 0, 103, 73, 76, 5, 45, 93, 87, 45, 69, 34, 59, 93, 59, 25, 66, 2, 59, 47, 54, 52, 71, 37, 66, 61, 49, 31, 97, 87, 66, 65, 58, 26, 66, 33, 33, 15, 44, 7, 68, 67, 96, 35, 24, 31, 21, 77, 77, 102, 33, 62, 59, 6, 29, 75, 99, 68, 31, 98, 103, 26, 100, 101, 38, 73, 11, 90, 27, 42, 36, 26, 24, 100, 22, 66, 81, 52, 54, 54, 10, 10, 81, 100, 49, 78, 34, 38, 80, 56, 94, 60, 96, 51]


## Для numpy

In [9]:
products_np = np.array(['автомобиль HAVAL', 'обувь', 'одежда', 'телефоны'])
prices_np = np.array([20000, 3000, 45600, 5000])

In [10]:
auto_sales_np = np.array(auto_sales)
auto_sales_np

array([62, 36,  5, ..., 27, 80, 28])

In [11]:
print(sum(auto_sales_np), int(sum(auto_sales_np)) * 20000)

5153385 103067700000


In [12]:
shoes_sales_np = np.array(shoes_sales)
shoes_sales_np

array([ 10,  18,  10, ...,  60,  26, 102])

In [13]:
print(sum(shoes_sales_np), int(sum(shoes_sales_np)) * 3000)

5168074 15504222000


In [14]:
clothes_sales_np = np.array(clothes_sales)
clothes_sales_np

array([27, 19, 55, ..., 62, 51, 80])

In [15]:
summ=sum(clothes_sales_np)
print(summ)

5153681


In [16]:
print (int(summ) * 45600)

235007853600


In [17]:
mobile_sales_np = np.array(mobile_sales)
mobile_sales_np

array([ 0, 29, 90, ..., 13, 30, 98])

In [18]:
print(sum(mobile_sales_np), int(sum(mobile_sales_np)) * 5000)

5140521 25702605000


In [19]:
sales_arrays = [auto_sales, shoes_sales, clothes_sales, mobile_sales]
sales_np = np.array(sales_arrays)

In [20]:
sales_np_v = np.vstack((auto_sales_np, shoes_sales_np, clothes_sales_np, mobile_sales_np))

## Pure_Python

In [21]:
sales = [auto_sales, shoes_sales, clothes_sales, mobile_sales]
total_income = [sum(sale) * price for sale, price in zip(sales, prices)]

for product, total in zip(products, total_income):
    print(f"Доход для {product} = {total}")

Доход для автомобиль HAVAL = 103067700000
Доход для обувь = 15504222000
Доход для одежда = 235007853600
Доход для телефоны = 25702605000


In [22]:
%timeit total_income = [sum(sale) * price for sale, price in zip(sales, prices)]

1.74 ms ± 21.9 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


## NumPy

In [23]:
total_income = [0] * len(prices_np) # Создаем список из нулей

def calculate_income():
    for i in range(len(prices_np)):
        total_income[i] = int(np.sum(sales_np[i])) * int(prices_np[i])

calculate_income()

print("\nNumpy без векторизации:")
for product, income in zip(products_np, total_income):
    print(f"Доход для {product} = {income}")

%timeit calculate_income()


Numpy без векторизации:
Доход для автомобиль HAVAL = 103067700000
Доход для обувь = 15504222000
Доход для одежда = 235007853600
Доход для телефоны = 25702605000
107 µs ± 1.68 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


## Numpy_Vectorize

In [24]:
def compute_income():
    incomes = np.sum(sales_np_v, axis=1)
    return [int(income) * int(price) for income, price in zip(incomes, prices_np)]

total_income_vectorized = compute_income()
for product, income in zip(products_np, total_income_vectorized):
    print(f"Доход для {product} = {income}")

%timeit compute_income()

Доход для автомобиль HAVAL = 103067700000
Доход для обувь = 15504222000
Доход для одежда = 235007853600
Доход для телефоны = 25702605000
94.2 µs ± 2.96 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


Из данных результатов видно, что использование Numpy с векторизацией тратит меньше всего времени

<h1>Задание 2</h1>

Необходимо написать с использованием numpy реализацию одного из следующих алгоритмов: 

- heapsort (вариант: 1,5,9,13,17,21)

- mergesort (вариант: 2,6,10,14,18,22)

- stable (вариант: 3,7,11,15,19)

- quicksort (вариант: 4,8,12,16,20) 

Сравнить скорость выполнения этих алгоритмов на чистом python, вашей реализации и numpy.sort() 

## Рассмотрим сортировку вставкой

In [25]:
numbers = [random.randint(0, 10000) for i in range(20000)]
numbers

[6040,
 2959,
 328,
 389,
 5706,
 3859,
 7853,
 4287,
 9742,
 4189,
 56,
 3893,
 3747,
 2083,
 1271,
 9445,
 8341,
 4787,
 6583,
 5306,
 6130,
 6723,
 2211,
 42,
 3601,
 5078,
 6519,
 312,
 4757,
 2783,
 1298,
 6146,
 7298,
 8772,
 8241,
 9038,
 5630,
 2330,
 1711,
 2883,
 172,
 8357,
 5897,
 7786,
 4561,
 892,
 1308,
 4974,
 3628,
 6144,
 7392,
 1731,
 9175,
 7843,
 4776,
 9003,
 3275,
 1769,
 1270,
 1473,
 5546,
 66,
 2907,
 9402,
 233,
 1828,
 3172,
 2901,
 1859,
 2364,
 6915,
 6146,
 9978,
 8455,
 7925,
 8645,
 3928,
 6052,
 2127,
 7885,
 7660,
 7311,
 320,
 742,
 6960,
 3901,
 4285,
 8967,
 4986,
 4873,
 8240,
 4784,
 1065,
 3256,
 6981,
 2850,
 706,
 4059,
 9083,
 3625,
 1607,
 3222,
 847,
 9728,
 7154,
 5368,
 6668,
 1116,
 9913,
 2383,
 9676,
 1103,
 4932,
 5104,
 3030,
 5945,
 2427,
 4512,
 416,
 1216,
 7332,
 6869,
 5478,
 6974,
 7207,
 4525,
 3685,
 5893,
 4126,
 7850,
 917,
 4100,
 1526,
 2423,
 7767,
 6345,
 8328,
 5841,
 9825,
 696,
 2288,
 4538,
 3797,
 8228,
 7302,
 714

In [26]:
def insertion_sort(arr):
    for i in range(1, len(arr)):
        key = arr[i]
        j = i - 1
        while j >=0 and key < arr[j]:
            arr[j + 1] = arr[j]
            j -= 1
        arr[j + 1] = key
    return arr



pure_python_insertion = insertion_sort(numbers)
print(pure_python_insertion, '\n')



[1, 2, 2, 3, 3, 4, 5, 5, 5, 5, 6, 6, 6, 7, 7, 7, 8, 8, 8, 8, 9, 9, 10, 10, 10, 10, 12, 12, 12, 13, 14, 14, 15, 16, 17, 17, 17, 17, 18, 18, 18, 19, 20, 20, 21, 21, 22, 23, 23, 23, 24, 24, 24, 24, 24, 24, 25, 25, 26, 26, 26, 26, 27, 27, 27, 28, 28, 28, 28, 28, 29, 29, 30, 31, 32, 32, 32, 32, 32, 32, 32, 33, 33, 34, 34, 34, 36, 36, 37, 38, 38, 38, 38, 39, 39, 39, 40, 40, 40, 40, 41, 41, 42, 43, 43, 44, 44, 44, 45, 45, 46, 47, 48, 49, 49, 49, 49, 50, 50, 54, 55, 55, 56, 56, 58, 59, 60, 62, 62, 62, 62, 62, 63, 63, 63, 63, 63, 63, 64, 64, 64, 64, 65, 65, 65, 65, 66, 66, 67, 68, 69, 70, 70, 70, 71, 72, 72, 73, 73, 73, 73, 74, 74, 74, 75, 76, 76, 76, 76, 77, 77, 77, 77, 77, 78, 78, 79, 80, 80, 80, 81, 81, 82, 82, 82, 83, 84, 84, 85, 86, 87, 88, 90, 91, 91, 91, 91, 92, 92, 92, 92, 93, 93, 93, 93, 93, 95, 95, 95, 97, 98, 98, 98, 98, 99, 99, 99, 99, 99, 101, 101, 101, 102, 103, 104, 104, 104, 105, 105, 105, 105, 106, 106, 106, 106, 107, 108, 109, 111, 111, 112, 112, 112, 112, 112, 112, 112, 112, 

In [27]:
%timeit insertion_sort(numbers)

2.16 ms ± 22.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [29]:
def insertion_sort_numpy(arr):
    arr = np.array(arr)
    for i in range(1, arr.shape[0]):
        key = arr[i]
        j = i - 1
        while j >= 0 and key < arr[j]:
            arr[j + 1] = arr[j]
            j -= 1
        arr[j + 1] = key
    return arr

my_np_insertion = insertion_sort_numpy(numbers)
print(my_np_insertion, '\n',)
%timeit insertion_sort_numpy(numbers)

[    1     2     2 ...  9999 10000 10000] 

7.87 ms ± 70 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [30]:
np_insertion = np.sort(numbers) 
print(np_insertion)
%timeit np.sort(numbers)

[    1     2     2 ...  9999 10000 10000]
1.02 ms ± 32.3 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


*Самый оптимальный вариант - сортировка np.sort*

<h1>Задание 3</h1> 

У нас есть данные о потреблении алкоголя о потреблнеии Алкоголя в мире https://github.com/fivethirtyeight/data/tree/master/alcohol-consumption. 

Давайте представим эти данные в виде структурированных массивов и определим, где же люди пьют больше вина, пива и других спиртных напитков.

In [31]:
import numpy as np

with open('drinks.csv', 'r') as f:
    data = f.readlines()[1:]
    
countries = []
beer_servings = []
spirit_servings = []
wine_servings = []
total_litres_of_pure_alcohol = []

for line in data:
    country, beer, spirit, wine, total = line.strip().split(',')
    countries.append(country)
    beer_servings.append(int(beer))
    spirit_servings.append(int(spirit))
    wine_servings.append(int(wine))
    total_litres_of_pure_alcohol.append(float(total))

countries = np.array(countries)
beer_servings = np.array(beer_servings)
spirit_servings = np.array(spirit_servings)
wine_servings = np.array(wine_servings)
total_litres_of_pure_alcohol = np.array(total_litres_of_pure_alcohol)

In [32]:
max_beer_idx = np.argmax(beer_servings)
max_beer_country = countries[max_beer_idx]

max_spirit_idx = np.argmax(spirit_servings)
max_spirit_country = countries[max_spirit_idx]

max_wine_idx = np.argmax(wine_servings)
max_wine_country = countries[max_wine_idx]


In [33]:
print(f"Пьют больше всего пива: {max_beer_country}")
print(f"Пьют больше всего спиртных напитков: {max_spirit_country}")
print(f"Пьют больше всего вина: {max_wine_country}")

Пьют больше всего пива: Namibia
Пьют больше всего спиртных напитков: Grenada
Пьют больше всего вина: France


<h1>Задание 4</h1> 

У нас есть Полный каталог всех случаев, когда кто-то проклинал или истекал кровью в фильме Квентина Тарантино. https://github.com/fivethirtyeight/data/tree/master/tarantino

Давайте представим эти данные в виде структурированных массивов и определим:

- число проклятий, летальных исходов и их отношение по фильмам 

- частота употребления конкретных прокрятий 

- распределение времени между проклятиями 

In [34]:
import numpy as np


data = np.genfromtxt('tarantino.csv', delimiter=',', dtype=None, names=True, encoding='utf-8')


sorted_data = np.sort(data, order='minutes_in') 


unique_movies = np.unique(sorted_data['movie'])
for movie in unique_movies:
    movie_data = sorted_data[sorted_data['movie'] == movie]
    curses_count = np.sum(movie_data['type'] == 'word')
    deaths_count = np.sum(movie_data['type'] == 'death')
    print(f"Movie: {movie}")
    print(f"Curses: {curses_count}, Deaths: {deaths_count}, Ratio: {curses_count/deaths_count if deaths_count != 0 else 0}")


unique_words = np.unique(sorted_data['word'])
for word in unique_words:
    word_count = np.sum(sorted_data['word'] == word)
    print(f"Word: {word}, Count: {word_count}")


times = sorted_data['minutes_in']
time_diffs = np.diff(times)
print("Average time difference between curses:", np.mean(time_diffs))
print("Minimum time difference between curses:", np.min(time_diffs))
print("Maximum time difference between curses:", np.max(time_diffs))


Movie: Django Unchained
Curses: 262, Deaths: 47, Ratio: 5.574468085106383
Movie: Inglorious Basterds
Curses: 58, Deaths: 48, Ratio: 1.2083333333333333
Movie: Jackie Brown
Curses: 368, Deaths: 4, Ratio: 92.0
Movie: Kill Bill: Vol. 1
Curses: 57, Deaths: 63, Ratio: 0.9047619047619048
Movie: Kill Bill: Vol. 2
Curses: 69, Deaths: 11, Ratio: 6.2727272727272725
Movie: Pulp Fiction
Curses: 469, Deaths: 7, Ratio: 67.0
Movie: Reservoir Dogs
Curses: 421, Deaths: 10, Ratio: 42.1
Word: , Count: 190
Word: ass, Count: 140
Word: asses, Count: 4
Word: asshead, Count: 1
Word: asshole, Count: 10
Word: assholes, Count: 5
Word: bastard, Count: 10
Word: bastards, Count: 1
Word: bitch, Count: 64
Word: bitches, Count: 9
Word: bullshit, Count: 15
Word: chickenshit, Count: 1
Word: cockblockery, Count: 1
Word: cocksucker, Count: 2
Word: cunt, Count: 2
Word: cunts, Count: 1
Word: damn, Count: 37
Word: damned, Count: 3
Word: dick, Count: 14
Word: dickless, Count: 1
Word: dicks, Count: 5
Word: dumbass, Count: 1
Wor