In [1]:
import numpy as np

In [3]:
np.array([1,2,3], dtype = 'float16')

array([1., 2., 3.], dtype=float16)

In [6]:
a = np.zeros(shape = (3,4), dtype=int)
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [10]:
a [2,1] = 3.6
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 3, 0, 0]])

In [11]:
?np.ones

Signature: np.ones(shape, dtype=None, order='C', *, like=None)
Docstring:
Return a new array of given shape and type, filled with ones.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: C
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of ones with the given shape, dtype, and orde

In [12]:
np.ones(shape = (3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [15]:
np.random.random(size = (4, 5) )

array([[0.94413911, 0.63993159, 0.19648787, 0.80624046, 0.52743235],
       [0.7133781 , 0.10333602, 0.47725113, 0.6391094 , 0.52786139],
       [0.98195587, 0.53888274, 0.37751054, 0.95341122, 0.60642841],
       [0.06212837, 0.08425912, 0.6099037 , 0.37654418, 0.132546  ]])

In [24]:
?np.randon.random

Object `np.randon.random` not found.


In [19]:
np.eye(size = (5, 5))

TypeError: eye() got an unexpected keyword argument 'size'

In [27]:

?np.eye

Signature: np.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
Docstring:
Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of 

In [31]:
targ = np.random.randint(low = 1, high = 11, size = (2,3,4))
targ

array([[[ 6,  7,  3,  8],
        [ 5, 10,  8,  1],
        [ 1,  3,  1,  5]],

       [[ 2, 10,  7,  8],
        [ 7,  1,  2,  2],
        [ 6,  8,  5,  9]]])

In [34]:
targ.ndim
targ.shape
targ.size

24

In [49]:
x = np.random.randint(1,11,6)
x

array([ 1, 10, 10, 10,  6, 10])

In [55]:
d = np.arange(1,17)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [57]:
d = d.reshape(4,4)
d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [52]:
x.reshape(2,3)

array([[ 1, 10, 10],
       [10,  6, 10]])